#!/usr/bin/env ruby
require './student'
require './teacher'
require './book'
require './rental'
require './all_books'
require './utils'

def run_programme(option, option_text)
  person_type_question = 'Do you want to create a student (1) or a teacher (2)? [Input the number]: '
  while option != 7
    case option
    when 1
      Book::ALL_BOOKS.list_all_books
    when 2
      Person::ALL_PERSONS.list_all_people
    when 3
      p = 0
      loop do
        puts person_type_question
        p = gets.chomp.to_i
        break if [1, 2].include? p
      end
      create_person(p)
    when 4
      create_book
    when 5
      create_rental
    when 6
      list_rentals
    end
    puts option_text
    option = gets.chomp.to_i
    next
  end
  puts 'Thank you for using this app!'
end

def main
  puts "Welcome to School Libray App!\n"
  option_text = "
    Please choose an option by enterin a number:\n
    1 - List all books\n
    2 - List all people\n
    3 - Create a person\n
    4 - Create a book\n
    5 - Create a rental\n
    6 - List all rentals for a given person id\n
    7 - Exit\n
    "
  puts option_text
  option = gets.chomp.to_i
  run_programme(option, option_text)
end

main
