#!/usr/bin/env ruby
require './student'
require './teacher'
require './book'
def list_all_books
  Book.all_books.each do |book|
    puts "Title: #{book.title}, Author: #{book.author}"
  end
end

def list_all_people
  puts 'list of people'
end

def create_person(option)
  age = 0
  loop do
    print('Age: ')
    age = gets.chomp.to_i
    break if age.positive?
  end
  print 'Name: '
  name = gets.chomp
  case option
  when 1
    permission = ''
    loop do
      print 'Has parent permission? [Y/N]: '
      permission = gets.chomp
      break if %w[y n].include? permission.downcase
    end
    permission.downcase == 'y' ? Student.new(age, nil, name, true) : Student.new(age, nil, name, false)
  else
    print 'Specialization: '
    specialization = gets.chomp
    Teacher.new(age, specialization, name)
  end
  puts 'Person created successfully'
end

def create_book
  print 'Title: '
  title = gets.chomp
  print 'Author: '
  author = gets.chomp
  Book.new(title, author)
  puts 'Book created successfully'
end

def create_rental
  puts 'Rental created successfully'
end

def list_rentals
  puts 'list rentals.'
end

def main
  puts "Welcome to School Libray App!\n"
  option_text = "
    Please choose an option by enterin a number:\n
    1 - List all books\n
    2 - List all people\n
    3 - Create a person\n
    4 - Create a book\n
    5 - Create a rental\n
    6 - List all rentals for a given person id\n
    7 - Exit\n
    "
  person_type_question = 'Do you want to create a student (1) or a teacher (2)? [Input the number]: '
  loop do
    puts option_text
    option = gets.chomp.to_i
    case option
    when 1
      list_all_books
    when 2
      list_all_people
    when 3
      p = 0
      loop do
        puts person_type_question
        p = gets.chomp.to_i
        break if [1, 2].include? p
      end
      create_person(p)
    when 4
      create_book
    when 5
      create_rental
    when 6
      list_rentals
    when 7
      puts 'Thank you for using this app!'
      break
    else
      next
    end
  end
end
main
